require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'OpusDecodeExample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-opus-decode', :path => '../../react-native-opus-decode.podspec'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

end
